/**
 * Constants for breakpoint.
 */
export class BreakpointConstants {
  /**
   * Breakpoints that represent small device types.
   */
  public static readonly BREAKPOINT_SM: string = 'sm';
  /**
   * Breakpoints that represent middle device types.
   */
  public static readonly BREAKPOINT_MD: string = 'md';
  /**
   * Breakpoints that represent large device types.
   */
  public static readonly BREAKPOINT_LG: string = 'lg';
  /**
   * Middle device width.
   */
  public static readonly MIDDLE_DEVICE_WIDTH: number = 600;
  /**
   * Large device width.
   */
  public static readonly LARGE_DEVICE_WIDTH: number = 840;
  /**
   *  Loading Height SM
   */
  public static readonly LOADING_HEIGHT_SM: string = '60%';
  /**
   *  Loading Height MD
   */
  public static readonly LOADING_HEIGHT_MD: string = '60%';
  /**
   *  Loading Height LG
   */
  public static readonly LOADING_HEIGHT_LG: string = '50%';
}